#**K-Nearest Neighbour**

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [0]:
dataset = pd.read_excel("Dataset_set_2_for_classification.xlsx")

In [0]:
dataset

1      2     3           4            5   ... 50 51 52 53 54
0     YEAR  MONTH  DATE  RADIO FLUX  SUN SPOT NO  ...  s  1  2  3  4
1     1997      6     2          77           35  ...  0  0  0  0  0
2     1997      6     3          75           20  ...  0  0  0  0  0
3     1997      6     4          74           16  ...  0  0  0  0  0
4     1997      6     5          74           15  ...  0  0  0  0  0
...    ...    ...   ...         ...          ...  ... .. .. .. .. ..
8375  2020      5     6          70            0  ...  0  0  0  0  0
8376  2020      5     7          69            0  ...  0  0  0  0  0
8377  2020      5     8          68            0  ...  0  0  0  0  0
8378  2020      5     9          71            0  ...  0  0  0  0  0
8379  2020      5    10          68            0  ...  0  0  0  0  0

[8380 rows x 54 columns]

# For c-class solar flares

In [0]:
X = dataset.iloc[1:, 0:38].values
y = dataset.iloc[1:, 46].values

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state = 0)

In [0]:
from sklearn.preprocessing import StandardScaler
sc_X_train = StandardScaler()
sc_y_train = StandardScaler()
X_train = sc_X_train.fit_transform(X_train)
X_test = sc_X_train.transform(X_test)
#y_train = sc_y_train.fit_transform(y_train)
#y_test = sc_y_train.transform(X_test)

In [0]:
y_train=np.asarray(y_train,dtype=float)

In [0]:
# Fitting K-NN to the Training set
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

In [0]:
y_pred = classifier.predict(X_test)
y_pred = np.asarray(y_pred,dtype=int)

In [0]:
y_test=np.asarray(y_test,dtype=int)

In [0]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1426,  224],
       [ 373, 1329]])

In [0]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.79      0.86      0.83      1650
           1       0.86      0.78      0.82      1702

    accuracy                           0.82      3352
   macro avg       0.82      0.82      0.82      3352
weighted avg       0.82      0.82      0.82      3352



#For m-class solar flares

Not using c-class flare data

In [0]:
X = dataset.iloc[1:, 0:38].values
y = dataset.iloc[1:, 47].values

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [0]:
from sklearn.preprocessing import StandardScaler
sc_X_train = StandardScaler()
sc_y_train = StandardScaler()
X_train = sc_X_train.fit_transform(X_train)
X_test = sc_X_train.transform(X_test)
#y_train = sc_y_train.fit_transform(y_train)
#y_test = sc_y_train.transform(X_test)

In [0]:
y_train=np.asarray(y_train,dtype=float)

In [0]:
# Fitting K-NN to the Training set
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [0]:
y_pred = classifier.predict(X_test)
y_pred = np.asarray(y_pred,dtype=int)

In [0]:
y_test=np.asarray(y_test,dtype=int)

In [0]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1378,   46],
       [ 199,   53]])

In [0]:
#for n=3  train:test = 6:4
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.88      0.95      0.92      2858
           1       0.48      0.26      0.34       494

    accuracy                           0.85      3352
   macro avg       0.68      0.61      0.63      3352
weighted avg       0.82      0.85      0.83      3352



In [0]:
#for n=5  train:test = 6:4
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.88      0.97      0.92      2858
           1       0.52      0.21      0.30       494

    accuracy                           0.86      3352
   macro avg       0.70      0.59      0.61      3352
weighted avg       0.82      0.86      0.83      3352



In [0]:
#for n=10  train:test = 6:4
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.87      0.99      0.92      2858
           1       0.63      0.13      0.22       494

    accuracy                           0.86      3352
   macro avg       0.75      0.56      0.57      3352
weighted avg       0.83      0.86      0.82      3352



In [0]:
# For n=5 and train:test = 8:2
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.87      0.97      0.92      1424
           1       0.54      0.21      0.30       252

    accuracy                           0.85      1676
   macro avg       0.70      0.59      0.61      1676
weighted avg       0.82      0.85      0.83      1676



**Using c-class Solar flare data**

In [0]:
X = dataset.iloc[1:, 0:39].values
y = dataset.iloc[1:, 47].values

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state = 0)

In [0]:
from sklearn.preprocessing import StandardScaler
sc_X_train = StandardScaler()
sc_y_train = StandardScaler()
X_train = sc_X_train.fit_transform(X_train)
X_test = sc_X_train.transform(X_test)
#y_train = sc_y_train.fit_transform(y_train)
#y_test = sc_y_train.transform(X_test)

In [0]:
y_train=np.asarray(y_train,dtype=float)

In [0]:
# Fitting K-NN to the Training set
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [0]:
y_pred = classifier.predict(X_test)
y_pred = np.asarray(y_pred,dtype=int)

In [0]:
y_test=np.asarray(y_test,dtype=int)

In [0]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[2754,  104],
       [ 375,  119]])

In [0]:
#for n=5  train:test = 6:4
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.88      0.96      0.92      2858
           1       0.53      0.24      0.33       494

    accuracy                           0.86      3352
   macro avg       0.71      0.60      0.63      3352
weighted avg       0.83      0.86      0.83      3352



In [0]:
#for n=5  train:test = 8:2
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.88      0.96      0.92      1424
           1       0.53      0.24      0.33       252

    accuracy                           0.85      1676
   macro avg       0.70      0.60      0.63      1676
weighted avg       0.83      0.85      0.83      1676



#**For x-class solar flares**

**Not using c-class & m-class Solar flares data**

In [0]:
X = dataset.iloc[1:, 0:38].values
y = dataset.iloc[1:, 48].values

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [0]:
from sklearn.preprocessing import StandardScaler
sc_X_train = StandardScaler()
sc_y_train = StandardScaler()
X_train = sc_X_train.fit_transform(X_train)
X_test = sc_X_train.transform(X_test)
#y_train = sc_y_train.fit_transform(y_train)
#y_test = sc_y_train.transform(X_test)

In [0]:
y_train=np.asarray(y_train,dtype=float)

In [0]:
# Fitting K-NN to the Training set
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [0]:
y_pred = classifier.predict(X_test)
y_pred = np.asarray(y_pred,dtype=int)

In [0]:
y_test=np.asarray(y_test,dtype=int)

In [0]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1648,    0],
       [  27,    1]])

In [0]:
#for n=5  train:test = 6:4
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99      3292
           1       0.50      0.02      0.03        60

    accuracy                           0.98      3352
   macro avg       0.74      0.51      0.51      3352
weighted avg       0.97      0.98      0.97      3352



In [0]:
#for n=5  train:test = 8:2
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99      1648
           1       1.00      0.04      0.07        28

    accuracy                           0.98      1676
   macro avg       0.99      0.52      0.53      1676
weighted avg       0.98      0.98      0.98      1676



**Using c-class Solar flares data**

In [0]:
X = dataset.iloc[1:, 0:39].values
y = dataset.iloc[1:, 48].values

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [0]:
from sklearn.preprocessing import StandardScaler
sc_X_train = StandardScaler()
sc_y_train = StandardScaler()
X_train = sc_X_train.fit_transform(X_train)
X_test = sc_X_train.transform(X_test)
#y_train = sc_y_train.fit_transform(y_train)
#y_test = sc_y_train.transform(X_test)

In [0]:
y_train=np.asarray(y_train,dtype=float)

In [0]:
# Fitting K-NN to the Training set
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [0]:
y_pred = classifier.predict(X_test)
y_pred = np.asarray(y_pred,dtype=int)

In [0]:
y_test=np.asarray(y_test,dtype=int)

In [0]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1648,    0],
       [  27,    1]])

In [0]:
#for n=5  train:test = 5:5
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99      4115
           1       0.67      0.03      0.05        75

    accuracy                           0.98      4190
   macro avg       0.82      0.51      0.52      4190
weighted avg       0.98      0.98      0.97      4190



In [0]:
#for n=5  train:test = 6:4
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99      3292
           1       0.67      0.03      0.06        60

    accuracy                           0.98      3352
   macro avg       0.82      0.52      0.53      3352
weighted avg       0.98      0.98      0.97      3352



In [0]:
#for n=5  train:test = 8:2
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99      1648
           1       1.00      0.04      0.07        28

    accuracy                           0.98      1676
   macro avg       0.99      0.52      0.53      1676
weighted avg       0.98      0.98      0.98      1676



**Using c-class & m-class Solar flares data**

In [0]:
X = dataset.iloc[1:, 0:40].values
y = dataset.iloc[1:, 48].values

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [0]:
from sklearn.preprocessing import StandardScaler
sc_X_train = StandardScaler()
sc_y_train = StandardScaler()
X_train = sc_X_train.fit_transform(X_train)
X_test = sc_X_train.transform(X_test)
#y_train = sc_y_train.fit_transform(y_train)
#y_test = sc_y_train.transform(X_test)

In [0]:
y_train=np.asarray(y_train,dtype=float)

In [0]:
# Fitting K-NN to the Training set
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [0]:
y_pred = classifier.predict(X_test)
y_pred = np.asarray(y_pred,dtype=int)

In [0]:
y_test=np.asarray(y_test,dtype=int)

In [0]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

In [0]:
#for n=5  train:test = 5:5
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99      4115
           1       0.75      0.04      0.08        75

    accuracy                           0.98      4190
   macro avg       0.87      0.52      0.53      4190
weighted avg       0.98      0.98      0.97      4190



In [0]:
#for n=5  train:test = 6:4
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99      3292
           1       0.75      0.05      0.09        60

    accuracy                           0.98      3352
   macro avg       0.87      0.52      0.54      3352
weighted avg       0.98      0.98      0.98      3352

