#**Naive Bayes**

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [0]:
dataset = pd.read_excel("Dataset_set_2_for_classification.xlsx")

In [3]:
dataset

1      2     3           4   ... 53 54           55             56
0     YEAR  MONTH  DATE  RADIO FLUX  ...  3  4  x-ray class  optical class
1     1997      6     2          77  ...  0  0            0              0
2     1997      6     3          75  ...  0  0            0              0
3     1997      6     4          74  ...  0  0            0              0
4     1997      6     5          74  ...  0  0            0              0
...    ...    ...   ...         ...  ... .. ..          ...            ...
8375  2020      5     6          70  ...  0  0            0              0
8376  2020      5     7          69  ...  0  0            0              0
8377  2020      5     8          68  ...  0  0            0              0
8378  2020      5     9          71  ...  0  0            0              0
8379  2020      5    10          68  ...  0  0            0              0

[8380 rows x 56 columns]

# For c-class solar flares

In [0]:
X = dataset.iloc[1:, 0:38].values
y = dataset.iloc[1:, 46].values

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.8, random_state = 0)

In [0]:
from sklearn.preprocessing import StandardScaler
sc_X_train = StandardScaler()
sc_y_train = StandardScaler()
X_train = sc_X_train.fit_transform(X_train)
X_test = sc_X_train.transform(X_test)
#y_train = sc_y_train.fit_transform(y_train)
#y_test = sc_y_train.transform(X_test)

In [0]:
y_train=np.asarray(y_train,dtype=float)

In [16]:
# Fitting Naive Bayes to the Training set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [0]:
y_pred = classifier.predict(X_test)
y_pred = np.asarray(y_pred,dtype=int)

In [0]:
y_test=np.asarray(y_test,dtype=int)

In [19]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[2999,  307],
       [1293, 2105]])

In [20]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.70      0.91      0.79      3306
           1       0.87      0.62      0.72      3398

    accuracy                           0.76      6704
   macro avg       0.79      0.76      0.76      6704
weighted avg       0.79      0.76      0.76      6704



#For m-class solar flares

Not using c-class flare data

In [0]:
X = dataset.iloc[1:, 0:38].values
y = dataset.iloc[1:, 47].values

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [0]:
from sklearn.preprocessing import StandardScaler
sc_X_train = StandardScaler()
sc_y_train = StandardScaler()
X_train = sc_X_train.fit_transform(X_train)
X_test = sc_X_train.transform(X_test)
#y_train = sc_y_train.fit_transform(y_train)
#y_test = sc_y_train.transform(X_test)

In [0]:
y_train=np.asarray(y_train,dtype=float)

In [25]:
# Fitting Naive Bayes to the Training set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [0]:
y_pred = classifier.predict(X_test)
y_pred = np.asarray(y_pred,dtype=int)

In [0]:
y_test=np.asarray(y_test,dtype=int)

In [28]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1245,  179],
       [ 156,   96]])

In [29]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.89      0.87      0.88      1424
           1       0.35      0.38      0.36       252

    accuracy                           0.80      1676
   macro avg       0.62      0.63      0.62      1676
weighted avg       0.81      0.80      0.80      1676



**Using c-class Solar flare data**

In [0]:
X = dataset.iloc[1:, 0:39].values
y = dataset.iloc[1:, 47].values

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state = 0)

In [0]:
from sklearn.preprocessing import StandardScaler
sc_X_train = StandardScaler()
sc_y_train = StandardScaler()
X_train = sc_X_train.fit_transform(X_train)
X_test = sc_X_train.transform(X_test)
#y_train = sc_y_train.fit_transform(y_train)
#y_test = sc_y_train.transform(X_test)

In [0]:
y_train=np.asarray(y_train,dtype=float)

In [52]:
# Fitting Naive Bayes to the Training set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [0]:
y_pred = classifier.predict(X_test)
y_pred = np.asarray(y_pred,dtype=int)

In [0]:
y_test=np.asarray(y_test,dtype=int)

In [55]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[2515,  343],
       [ 290,  204]])

In [56]:
# train:test = 6:4
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.90      0.88      0.89      2858
           1       0.37      0.41      0.39       494

    accuracy                           0.81      3352
   macro avg       0.63      0.65      0.64      3352
weighted avg       0.82      0.81      0.82      3352



#**For x-class solar flares**

**Not using c-class & m-class Solar flares data**

In [0]:
X = dataset.iloc[1:, 0:38].values
y = dataset.iloc[1:, 48].values

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state = 0)

In [0]:
from sklearn.preprocessing import StandardScaler
sc_X_train = StandardScaler()
sc_y_train = StandardScaler()
X_train = sc_X_train.fit_transform(X_train)
X_test = sc_X_train.transform(X_test)
#y_train = sc_y_train.fit_transform(y_train)
#y_test = sc_y_train.transform(X_test)

In [0]:
y_train=np.asarray(y_train,dtype=float)

In [70]:
# Fitting Naive Bayes to the Training set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [0]:
y_pred = classifier.predict(X_test)
y_pred = np.asarray(y_pred,dtype=int)

In [0]:
y_test=np.asarray(y_test,dtype=int)

In [73]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[2934,  358],
       [  29,   31]])

In [65]:
#for train:test = 8:2
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.89      0.94      1648
           1       0.07      0.50      0.12        28

    accuracy                           0.88      1676
   macro avg       0.53      0.69      0.53      1676
weighted avg       0.98      0.88      0.92      1676



In [74]:
#for train:test = 6:4
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.89      0.94      3292
           1       0.08      0.52      0.14        60

    accuracy                           0.88      3352
   macro avg       0.53      0.70      0.54      3352
weighted avg       0.97      0.88      0.92      3352



**Using c-class Solar flares data**

In [0]:
X = dataset.iloc[1:, 0:39].values
y = dataset.iloc[1:, 48].values

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state = 0)

In [0]:
from sklearn.preprocessing import StandardScaler
sc_X_train = StandardScaler()
sc_y_train = StandardScaler()
X_train = sc_X_train.fit_transform(X_train)
X_test = sc_X_train.transform(X_test)
#y_train = sc_y_train.fit_transform(y_train)
#y_test = sc_y_train.transform(X_test)

In [0]:
y_train=np.asarray(y_train,dtype=float)

In [96]:
# Fitting Naive Bayes to the Training set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [0]:
y_pred = classifier.predict(X_test)
y_pred = np.asarray(y_pred,dtype=int)

In [0]:
y_test=np.asarray(y_test,dtype=int)

In [99]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[2931,  361],
       [  29,   31]])

In [83]:
#for n=5  train:test = 8:2
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.89      0.94      1648
           1       0.07      0.50      0.12        28

    accuracy                           0.88      1676
   macro avg       0.53      0.69      0.53      1676
weighted avg       0.98      0.88      0.92      1676



In [100]:
#for n=5  train:test = 6:4
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.89      0.94      3292
           1       0.08      0.52      0.14        60

    accuracy                           0.88      3352
   macro avg       0.53      0.70      0.54      3352
weighted avg       0.97      0.88      0.92      3352



**Using c-class & m-class Solar flares data**

In [0]:
X = dataset.iloc[1:, 0:40].values
y = dataset.iloc[1:, 48].values

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state = 0)

In [0]:
from sklearn.preprocessing import StandardScaler
sc_X_train = StandardScaler()
sc_y_train = StandardScaler()
X_train = sc_X_train.fit_transform(X_train)
X_test = sc_X_train.transform(X_test)
#y_train = sc_y_train.fit_transform(y_train)
#y_test = sc_y_train.transform(X_test)

In [0]:
y_train=np.asarray(y_train,dtype=float)

In [122]:
# Fitting Naive Bayes to the Training set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [0]:
y_pred = classifier.predict(X_test)
y_pred = np.asarray(y_pred,dtype=int)

In [0]:
y_test=np.asarray(y_test,dtype=int)

In [125]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[2933,  359],
       [  27,   33]])

In [109]:
#for train:test = 8:2
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.89      0.94      1648
           1       0.08      0.54      0.13        28

    accuracy                           0.88      1676
   macro avg       0.53      0.71      0.53      1676
weighted avg       0.98      0.88      0.92      1676



In [126]:
#for train:test = 6:4
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.89      0.94      3292
           1       0.08      0.55      0.15        60

    accuracy                           0.88      3352
   macro avg       0.54      0.72      0.54      3352
weighted avg       0.97      0.88      0.92      3352

